<?xml version="1.0" encoding="utf-8"?><Database Name="miniproject" Class="bookstoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=miniproject;Integrated Security=True;Encrypt=True" SettingsObjectName="miniproj.Properties.Settings" SettingsPropertyName="miniprojectConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bookstore" Member="bookstores">
    <Type Name="bookstore">
      <Column Name="isbn" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tacgia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nhaxuatban" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Thangban" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>