#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miniproj
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="miniproject")]
	public partial class bookDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbook(book instance);
    partial void Updatebook(book instance);
    partial void Deletebook(book instance);
    #endregion
		
		public bookDataContext() : 
				base(global::miniproj.Properties.Settings.Default.miniprojectConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bookDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<book> books
		{
			get
			{
				return this.GetTable<book>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book")]
	public partial class book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _isbn;
		
		private string _Tensach;
		
		private string _Tacgia;
		
		private string _Nhaxuatban;
		
		private string _Gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnisbnChanging(string value);
    partial void OnisbnChanged();
    partial void OnTensachChanging(string value);
    partial void OnTensachChanged();
    partial void OnTacgiaChanging(string value);
    partial void OnTacgiaChanged();
    partial void OnNhaxuatbanChanging(string value);
    partial void OnNhaxuatbanChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    #endregion
		
		public book()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbn", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string isbn
		{
			get
			{
				return this._isbn;
			}
			set
			{
				if ((this._isbn != value))
				{
					this.OnisbnChanging(value);
					this.SendPropertyChanging();
					this._isbn = value;
					this.SendPropertyChanged("isbn");
					this.OnisbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tensach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tensach
		{
			get
			{
				return this._Tensach;
			}
			set
			{
				if ((this._Tensach != value))
				{
					this.OnTensachChanging(value);
					this.SendPropertyChanging();
					this._Tensach = value;
					this.SendPropertyChanged("Tensach");
					this.OnTensachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tacgia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tacgia
		{
			get
			{
				return this._Tacgia;
			}
			set
			{
				if ((this._Tacgia != value))
				{
					this.OnTacgiaChanging(value);
					this.SendPropertyChanging();
					this._Tacgia = value;
					this.SendPropertyChanged("Tacgia");
					this.OnTacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhaxuatban", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nhaxuatban
		{
			get
			{
				return this._Nhaxuatban;
			}
			set
			{
				if ((this._Nhaxuatban != value))
				{
					this.OnNhaxuatbanChanging(value);
					this.SendPropertyChanging();
					this._Nhaxuatban = value;
					this.SendPropertyChanged("Nhaxuatban");
					this.OnNhaxuatbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
