#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miniproj
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="miniproject")]
	public partial class deviceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdevice(device instance);
    partial void Updatedevice(device instance);
    partial void Deletedevice(device instance);
    #endregion
		
		public deviceDataContext() : 
				base(global::miniproj.Properties.Settings.Default.miniprojectConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public deviceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public deviceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public deviceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public deviceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<device> devices
		{
			get
			{
				return this.GetTable<device>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devices")]
	public partial class device : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Soseri;
		
		private string _Tenthietbi;
		
		private string _Mausach;
		
		private string _Namsanxuat;
		
		private string _Gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoseriChanging(string value);
    partial void OnSoseriChanged();
    partial void OnTenthietbiChanging(string value);
    partial void OnTenthietbiChanged();
    partial void OnMausachChanging(string value);
    partial void OnMausachChanged();
    partial void OnNamsanxuatChanging(string value);
    partial void OnNamsanxuatChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    #endregion
		
		public device()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soseri", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Soseri
		{
			get
			{
				return this._Soseri;
			}
			set
			{
				if ((this._Soseri != value))
				{
					this.OnSoseriChanging(value);
					this.SendPropertyChanging();
					this._Soseri = value;
					this.SendPropertyChanged("Soseri");
					this.OnSoseriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenthietbi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tenthietbi
		{
			get
			{
				return this._Tenthietbi;
			}
			set
			{
				if ((this._Tenthietbi != value))
				{
					this.OnTenthietbiChanging(value);
					this.SendPropertyChanging();
					this._Tenthietbi = value;
					this.SendPropertyChanged("Tenthietbi");
					this.OnTenthietbiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mausach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mausach
		{
			get
			{
				return this._Mausach;
			}
			set
			{
				if ((this._Mausach != value))
				{
					this.OnMausachChanging(value);
					this.SendPropertyChanging();
					this._Mausach = value;
					this.SendPropertyChanged("Mausach");
					this.OnMausachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namsanxuat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Namsanxuat
		{
			get
			{
				return this._Namsanxuat;
			}
			set
			{
				if ((this._Namsanxuat != value))
				{
					this.OnNamsanxuatChanging(value);
					this.SendPropertyChanging();
					this._Namsanxuat = value;
					this.SendPropertyChanged("Namsanxuat");
					this.OnNamsanxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
