<?xml version="1.0" encoding="utf-8"?><Database Name="miniproject" Class="deviceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=miniproject;Integrated Security=True;Encrypt=True" SettingsObjectName="miniproj.Properties.Settings" SettingsPropertyName="miniprojectConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.devices" Member="devices">
    <Type Name="device">
      <Column Name="Soseri" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenthietbi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mausach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Namsanxuat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>